Repository freelensapp/freelens, pull requests merged in 2025-09, with the labels that each got.

#1147 [feature]: force delete pod on terminating, failure, etc;
  packages/core/src/common/k8s-api/kube-object.store.ts
  packages/core/src/features/namespaces/__snapshots__/route-with-sub-namespaces.test.tsx.snap
  packages/core/src/features/namespaces/route-with-sub-namespaces.test.tsx
  packages/core/src/renderer/components/custom-resource-definitions/mixins.scss
  packages/core/src/renderer/components/dock/logs/__test__/pod.mock.ts
  packages/core/src/renderer/components/kube-object-menu/__snapshots__/kube-object-menu.test.tsx.snap
  packages/core/src/renderer/components/kube-object-menu/kube-object-delete-service.injectable.ts
  packages/core/src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
  packages/core/src/renderer/components/kube-object-menu/kube-object-menu.tsx
  packages/core/src/renderer/components/kube-object-menu/smart-delete-menu-item.tsx
  packages/core/src/renderer/components/namespaces/namespace-remove-context-menu-overriding-listener.injectable.ts
  packages/core/src/renderer/components/namespaces/namespaces-mixins.scss
  packages/core/src/renderer/components/workloads-jobs/jobs.tsx
  packages/core/src/renderer/components/workloads-overview/overview-workload-status.tsx
  packages/core/src/renderer/components/workloads/workloads-mixins.scss
  packages/kube-object/src/specifics/namespace.ts
  packages/kube-object/src/specifics/pod.ts
  packages/utility-features/kube-api/src/endpoints/pod.api.ts
  packages/utility-features/kube-api/src/kube-api.ts
Labels: enhancement, ux

#1207 Presents Ready/NotReady first on the conditions list
  packages/core/src/renderer/components/kube-object-conditions/components.tsx
  packages/core/src/renderer/components/kube-object-conditions/kube-object-conditions-list.tsx
  packages/core/src/renderer/components/nodes/nodes.scss
  packages/core/src/renderer/components/nodes/route.tsx
Labels: enhancement, ux, regression

#1212 Create namespace from template
  packages/resource-templates/templates/create-resource/Deployment.yaml
  packages/resource-templates/templates/create-resource/Namespace.yaml
Labels: enhancement, ux

#1213 Forced update dependency minimatch to ^5.0.0
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: security, updates

#1216 Dedicated paste handler for Monaco editor
  packages/core/src/main/electron-app/runnables/setup-paste-handler.injectable.ts
  packages/core/src/main/electron-app/runnables/setup-runnables-after-window-is-opened.injectable.ts
  patches/monaco-editor.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug, regression

#1229 Downgrade depedency node-gyp to 11.3.0
  freelens/package.json
  packages/core/package.json
  pnpm-lock.yaml
Labels: regression, updates

#1240 Disable pre/post scripts in release workflow
  .github/workflows/release.yaml
Labels: ci
