Repository freelensapp/freelens, pull requests merged in 2025-05, with the labels that each got.

#688 Correct dependencies for electron and pnpm
  knip.jsonc
  packages/core/package.json
  patches/circular-dependency-plugin.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug, regression

#690 Remove electron from ASAR explicitely
  freelens/electron-builder.yml
Labels: bug, distribution, regression

#693 Modify light theme for primary and sub menu active state colors
  packages/core/src/common/catalog-entities/general-catalog-entities/implementations/catalog-catalog-entity.injectable.ts
  packages/core/src/common/catalog-entities/general-catalog-entities/implementations/welcome-catalog-entity.injectable.ts
  packages/core/src/features/preferences/common/preferences-catalog-entity.injectable.ts
  packages/core/src/renderer/components/layout/sidebar-items.module.scss
  packages/core/src/renderer/themes/lens-light.injectable.ts
Labels: enhancement, ux

#708 Tweak transpiled version of node-fetch
  packages/core/src/common/fetch/fetch.injectable.ts
  packages/core/src/common/fetch/proxy-fetch.injectable.ts
  packages/transpilation/node-fetch/index.ts
Labels: bug, refactoring, esm

#724 Confirmation of namespace deletion
  packages/core/src/features/namespaces/route-with-sub-namespaces.test.tsx
  packages/core/src/renderer/components/namespaces/namespace-remove-context-menu-overriding-listener.injectable.ts
Labels: enhancement, ux

#740 Add pnpm as a dependency for root workspace
  knip.jsonc
  package.json
  pnpm-lock.yaml
Labels: bug

#745 build: replace cross-env with pnpm shell-emulator
  freelens/package.json
  package.json
  packages/core/package.json
  pnpm-workspace.yaml
Labels: refactoring

#767 Replace http-proxy with http-proxy-node16
  freelens/package.json
  knip.jsonc
  packages/core/package.json
  packages/core/src/main/cluster/kube-auth-proxy-server.injectable.ts
  packages/core/src/main/lens-proxy/lens-proxy.injectable.ts
  packages/core/src/main/lens-proxy/lens-proxy.ts
  packages/core/src/main/router/route.ts
  packages/core/src/main/routes/files/development.injectable.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: updates

#775 Use hub.helm.sh to fetch the list of Helm repos
  packages/core/src/features/helm-charts/child-features/preferences/renderer/adding-of-public-helm-repository/public-helm-repositories/request-public-helm-repositories.injectable.ts
Labels: rebranding, refactoring

#786 Align memory and CPU usage in pods table
  packages/core/src/renderer/components/workloads-pods/columns/pods-memory-usage-column.injectable.tsx
  packages/core/src/renderer/components/workloads-pods/pods.scss
  packages/utility-features/utilities/src/convert-memory.test.ts
  packages/utility-features/utilities/src/convertMemory.ts
Labels: ux

#788 Bugfix when helm repo update shows no repositories found
  packages/core/src/features/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  packages/core/src/main/helm/repositories/get-active-helm-repositories/get-active-helm-repositories.injectable.ts
Labels: bug
