Repository freelensapp/freelens, pull requests merged in 2025-03, with the labels that each got.

#234 Remove sentry and telemetry setting
  freelens/package.json
  freelens/src/common/application-information.injectable.ts
  package-lock.json
  packages/core/package.json
  packages/core/src/common/error-reporting/initialize-sentry-reporting.global-override-for-injectable.ts
  packages/core/src/common/error-reporting/initialize-sentry-reporting.injectable.ts
  packages/core/src/common/vars/sentry-dsn-url.injectable.ts
  packages/core/src/features/preferences/__snapshots__/navigation-to-telemetry-preferences.test.tsx.snap
  packages/core/src/features/preferences/common/navigate-to-telemetry-preferences.injectable.ts
  packages/core/src/features/preferences/navigation-to-telemetry-preferences.test.tsx
  packages/core/src/features/preferences/renderer/compliance-for-legacy-extension-api/registrator-for-preference-items.injectable.tsx
  packages/core/src/features/preferences/renderer/preference-items/telemetry/automatic-error-reporting/automatic-error-reporting-preference-item.injectable.ts
  packages/core/src/features/preferences/renderer/preference-items/telemetry/automatic-error-reporting/automatic-error-reporting.tsx
  packages/core/src/features/preferences/renderer/preference-items/telemetry/telemetry-preference-page.injectable.tsx
  packages/core/src/features/preferences/renderer/preference-items/telemetry/telemetry-preference-tab.injectable.ts
  packages/core/src/features/telemetry/emit-telemetry-from-specific-function-calls.test.ts
  packages/core/src/features/telemetry/renderer/emit-telemetry.injectable.ts
  packages/core/src/features/telemetry/renderer/telemetry-decorator-for-show-details.injectable.ts
  packages/core/src/features/telemetry/renderer/telemetry-decorator.global-override-for-injectable.ts
  packages/core/src/features/telemetry/renderer/telemetry-decorator.injectable.ts
  packages/core/src/features/telemetry/renderer/telemetry-white-list-for-parameterless-functions.injectable.ts
  packages/core/src/features/telemetry/show-details-calls.test.ts
  packages/core/src/main/start-main-application/runnables/sentry/initialize-on-main.global-override-for-injectable.ts
  packages/core/src/main/start-main-application/runnables/sentry/initialize-on-main.injectable.ts
  packages/core/src/main/start-main-application/runnables/sentry/setup.injectable.ts
  packages/core/src/renderer/before-frame-starts/runnables/setup-sentry.injectable.ts
  packages/core/src/test-env/application-information-fake.injectable.ts
  packages/technical-features/application/agnostic/src/application-information-token.no-coverage.ts
Labels: refactoring

#421 CI: Use cache for Electron
  .github/workflows/integration-tests.yaml
  .github/workflows/release.yaml
  .github/workflows/unit-tests.yaml
  .gitignore
Labels: ci

#446 Fix for problem that paste operation doesn't work in an editor
  package.json
  packages/core/src/renderer/components/cluster-manager/cluster-frame-handler.ts
  patches/monaco-editor+0.52.2.patch
Labels: bug, regression

#448 Remove text selection style causing readability issues in light theme
  packages/core/src/renderer/components/app.scss
Labels: enhancement, ux

#450 Upgrade @testing-library dependencies
  package-lock.json
  packages/business-features/keyboard-shortcuts/package.json
  packages/business-features/keyboard-shortcuts/src/keyboard-shortcuts.test.tsx
  packages/core/package.json
  packages/core/src/features/cluster/delete-dialog/delete-cluster-dialog.test.tsx
  packages/core/src/features/command-pallet/keyboard-shortcuts.test.tsx
  packages/core/src/features/helm-charts/add-helm-repository-from-list-in-preferences.test.ts
  packages/core/src/features/helm-charts/installing-chart/installing-helm-chart-from-new-tab.test.ts
  packages/core/src/features/helm-charts/installing-chart/opening-dock-tab-for-installing-helm-chart.test.ts
  packages/core/src/features/hotbar/hovering-hotbar-menu.test.ts
  packages/core/src/features/preferences/navigation-to-extension-specific-preferences.test.tsx
  packages/core/src/renderer/components/avatar/__tests__/avatar.test.tsx
  packages/core/src/renderer/components/catalog/__tests__/catalog-add-button.test.tsx
  packages/core/src/renderer/components/catalog/__tests__/catalog-category-label.test.tsx
  packages/core/src/renderer/components/cluster-settings/__tests__/cluster-local-terminal-settings.test.tsx
  packages/core/src/renderer/components/cluster-settings/__tests__/icon-settings.test.tsx
  packages/core/src/renderer/components/dock/logs/__test__/log-resource-selector.test.tsx
  packages/core/src/renderer/components/dock/logs/__test__/log-search.test.tsx
  packages/core/src/renderer/components/dock/logs/__test__/to-bottom.test.tsx
  packages/core/src/renderer/components/extensions/__tests__/extensions.test.tsx
  packages/core/src/renderer/components/hotbar/__tests__/hotbar-remove-command.test.tsx
  packages/core/src/renderer/components/kube-object-list-layout/kube-object-list-layout.test.tsx
  packages/core/src/renderer/components/kube-object-menu/kube-object-menu.test.tsx
  packages/core/src/renderer/components/layout/__tests__/sidebar-cluster.test.tsx
  packages/core/src/renderer/components/layout/top-bar/top-bar.test.tsx
  packages/core/src/renderer/components/select/select.test.tsx
  packages/core/src/renderer/components/switch/__tests__/switch.test.tsx
  packages/core/src/renderer/components/test-utils/get-application-builder.tsx
  packages/core/src/renderer/components/user-management/cluster-role-bindings/__tests__/dialog.test.tsx
  packages/core/src/renderer/components/user-management/role-bindings/__tests__/dialog.test.tsx
  packages/core/src/renderer/components/workloads-pods/__tests__/pod-tolerations.test.tsx
  packages/infrastructure/jest/package.json
  packages/routing/package.json
  packages/ui-components/button/package.json
  packages/ui-components/error-boundary/package.json
  packages/ui-components/icon/package.json
  packages/ui-components/tooltip/package.json
  packages/ui-components/tooltip/src/tooltip.test.tsx
  packages/ui-components/tooltip/src/withTooltip.test.tsx
  packages/utility-features/react-testing-library-discovery/package.json
Labels: refactoring

#484 Adapts themes to the newer @xterm/xterm and fixes selection in terminal
  packages/core/src/renderer/themes/lens-dark.injectable.ts
  packages/core/src/renderer/themes/lens-light.injectable.ts
  packages/core/src/renderer/themes/lens-theme.ts
Labels: bug, ux, regression

#491 Replaced deprecated navigation-related APIs in Electron
  packages/core/src/features/application-menu/main/menu-items/view/go-back/go-back-menu-item.injectable.ts
  packages/core/src/features/application-menu/main/menu-items/view/go-forward/go-forward-menu-item.injectable.ts
  packages/core/src/main/ipc/window.ts
  packages/core/src/main/start-main-application/lens-window/application-window/create-electron-window.injectable.ts
Labels: refactoring

#492 More file patterns are ignored during scanning kube folder, including kubectx and kubens caches
  packages/core/src/main/catalog-sources/kubeconfig-sync/watch-file-changes.injectable.ts
Labels: enhancement

#493 Less verbose warning about no Prometheus service found
  packages/core/src/main/routes/metrics/add-metrics-route.injectable.ts
Labels: ux

#482 Upgrade to MUI 5
  freelens/package.json
  package-lock.json
  packages/core/package.json
  packages/core/src/features/helm-charts/__snapshots__/add-custom-helm-repository-in-preferences.test.ts.snap
  packages/core/src/features/helm-charts/__snapshots__/add-helm-repository-from-list-in-preferences.test.ts.snap
  packages/core/src/features/helm-charts/__snapshots__/listing-active-helm-repositories-in-preferences.test.ts.snap
  packages/core/src/features/helm-charts/__snapshots__/remove-helm-repository-from-list-of-active-repository-in-preferences.test.ts.snap
  packages/core/src/renderer/components/catalog/__tests__/catalog-add-button.test.tsx
  packages/core/src/renderer/components/catalog/catalog-add-button.tsx
  packages/core/src/renderer/components/helm-charts/helm-chart-details.tsx
  packages/core/src/renderer/components/namespaces/__snapshots__/namespace-tree-view.test.tsx.snap
  packages/core/src/renderer/components/namespaces/namespace-tree-view.tsx
  packages/core/src/renderer/components/slider/slider.tsx
  packages/core/src/renderer/components/welcome/welcome.tsx
  packages/core/src/renderer/components/workloads-deployments/scale/dialog.tsx
  packages/core/src/renderer/components/workloads-replicasets/scale-dialog/dialog.tsx
  packages/core/src/renderer/components/workloads-replication-controllers/replication-controller-details.tsx
  packages/core/src/renderer/components/workloads-statefulsets/scale/dialog.tsx
  packages/core/src/renderer/frames/theme-provider-react-application-hoc.injectable.tsx
  packages/core/src/renderer/mui-base-theme.tsx
Labels: needs manual checks

#507 Removed carousel with welcome banners
  freelens/package.json
  package-lock.json
  packages/core/package.json
  packages/core/src/extensions/lens-renderer-extension.ts
  packages/core/src/features/welcome/banners-from-extension.test.tsx
  packages/core/src/renderer/components/welcome/welcome-banner-items/welcome-banner-items.injectable.ts
  packages/core/src/renderer/components/welcome/welcome-banner-items/welcome-banner-registration.ts
  packages/core/src/renderer/components/welcome/welcome.tsx
Labels: refactoring, updates
