Repository freelensapp/freelens, pull requests merged in 2025-08, with the labels that each got.

#1125 Columns with role name and ref types in RBAC bindings
  packages/core/src/extensions/renderer-api/components.ts
  packages/core/src/extensions/renderer-api/navigation.ts
  packages/core/src/renderer/components/kube-detail-params/get-maybe-details-url.injectable.ts
  packages/core/src/renderer/components/kube-object-link/index.ts
  packages/core/src/renderer/components/kube-object-link/link-to-cluster-role.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-namespace.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-object.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-role.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-secret.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-service-account.tsx
  packages/core/src/renderer/components/user-management/cluster-role-bindings/details.tsx
  packages/core/src/renderer/components/user-management/cluster-role-bindings/view.tsx
  packages/core/src/renderer/components/user-management/role-bindings/details.tsx
  packages/core/src/renderer/components/user-management/role-bindings/view.tsx
  packages/kube-object/src/specifics/cluster-role-binding.ts
  packages/kube-object/src/specifics/role-binding.ts
Labels: enhancement, ux

#1131 Add HTTPS support and custom prefix in Prometheus settings
  packages/core/src/common/catalog-entities/kubernetes-cluster.ts
  packages/core/src/common/cluster-types.ts
  packages/core/src/main/cluster/prometheus-handler/prometheus-handler.ts
  packages/core/src/renderer/components/cluster-settings/prometheus-setting.tsx
Labels: enhancement

#1136 Add hidden column with IP address in pod lists. Hide node and qos by default.
  packages/core/src/features/cluster/kube-object-details/extension-api/__snapshots__/disable-kube-object-detail-items-when-cluster-is-not-relevant.test.tsx.snap
  packages/core/src/features/cluster/kube-object-details/extension-api/__snapshots__/reactively-hide-kube-object-detail-item.test.tsx.snap
  packages/core/src/features/cluster/workloads/__snapshots__/pods.test.tsx.snap
  packages/core/src/renderer/components/item-object-list/list-layout.tsx
  packages/core/src/renderer/components/kube-object-link/index.ts
  packages/core/src/renderer/components/kube-object-link/link-to-node.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-pod.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-priority-class.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-replica-set.tsx
  packages/core/src/renderer/components/kube-object-link/link-to-runtime-class.tsx
  packages/core/src/renderer/components/kube-object-list-layout/__snapshots__/kube-object-list-layout.test.tsx.snap
  packages/core/src/renderer/components/kube-object-meta/kube-object-meta.tsx
  packages/core/src/renderer/components/workloads-deployments/deployment-replicasets.tsx
  packages/core/src/renderer/components/workloads-deployments/deployments.scss
  packages/core/src/renderer/components/workloads-deployments/deployments.tsx
  packages/core/src/renderer/components/workloads-pods/columns/column-priority.ts
  packages/core/src/renderer/components/workloads-pods/columns/pods-ip-column.injectable.tsx
  packages/core/src/renderer/components/workloads-pods/columns/pods-node-column.injectable.tsx
  packages/core/src/renderer/components/workloads-pods/pod-details-list.tsx
  packages/core/src/renderer/components/workloads-pods/pod-details.tsx
  packages/core/src/renderer/components/workloads-pods/pods.scss
  packages/core/src/renderer/components/workloads-pods/pods.tsx
Labels: enhancement, ux

#1141 Field name renamed from Susped to Resumed for Jobs and CronJobs
  packages/core/src/renderer/components/kube-object-link/index.ts
  packages/core/src/renderer/components/kube-object-link/link-to-job.tsx
  packages/core/src/renderer/components/workloads-cronjobs/cronjob-details.scss
  packages/core/src/renderer/components/workloads-cronjobs/cronjob-details.tsx
  packages/core/src/renderer/components/workloads-cronjobs/cronjobs.scss
  packages/core/src/renderer/components/workloads-cronjobs/cronjobs.tsx
  packages/core/src/renderer/components/workloads-jobs/job-details.tsx
  packages/core/src/renderer/components/workloads-jobs/jobs.scss
  packages/core/src/renderer/components/workloads-jobs/jobs.tsx
Labels: ux

#1146 Show only the first load balancer and the rule in the ingresses list
  packages/core/src/renderer/components/network-ingresses/ingresses.tsx
Labels: bug, ux
