Repository freelensapp/freelens, pull requests merged in 2025-04, with the labels that each got.

#614 CI: replace nick-fields/retry@v3 with retry task
  .github/workflows/integration-tests.yaml
  .github/workflows/kubectl-versions.yaml
  .github/workflows/linter.yaml
  .github/workflows/npm-audit.yaml
  .github/workflows/npm-dedupe.yaml
  .github/workflows/npm-version.yaml
  .github/workflows/release.yaml
  .github/workflows/trunk-upgrade.yaml
  .github/workflows/unit-tests.yaml
Labels: ci

#643 Fix Custom Resource Definition filter by group
  packages/core/src/renderer/components/custom-resource-definitions/selected-groups-url-param.injectable.ts
  packages/core/src/renderer/components/custom-resource-definitions/view.tsx
Labels: bug

#655 Rebranding for error messages and settings
  packages/core/src/extensions/extension-discovery/is-compatible-extension/is-compatible-extension.ts
  packages/core/src/features/application-update/__snapshots__/hiding-preference-when-disabled.test.ts.snap
  packages/core/src/features/application-update/child-features/application-update-using-application-menu/application-update-using-application-menu.test.ts
  packages/core/src/features/application-update/child-features/application-update-using-application-menu/main/check-for-updates-menu-item.injectable.ts
  packages/core/src/features/application-update/child-features/application-update-using-top-bar/renderer/update-application-top-bar-item/update-button/update-button.tsx
  packages/core/src/features/application-update/child-features/application-update-using-tray/installing-update-using-tray.test.ts
  packages/core/src/features/application-update/child-features/application-update-using-tray/main/tray-items/check-for-updates-tray-item.injectable.ts
  packages/core/src/features/cluster/delete-dialog/__snapshots__/delete-cluster-dialog.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/closing-preferences.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/extension-adding-preference-tabs.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/hiding-of-empty-branches.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-application-preferences.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-editor-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-extension-specific-preferences.test.tsx.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-kubernetes-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-proxy-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-to-terminal-preferences.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/features/preferences/__snapshots__/navigation-using-tray.test.ts.snap
  packages/core/src/features/preferences/renderer/preference-items/application/start-up/start-up.tsx
  packages/core/src/features/preferences/renderer/preference-items/proxy/allow-untrusted-certificates/allow-untrusted-certificates.tsx
  packages/core/src/features/preferences/renderer/preference-items/terminal/terminal-theme/terminal-theme.tsx
  packages/core/src/features/welcome/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/main/lens-proxy/lens-proxy-port.injectable.ts
  packages/core/src/main/lens-proxy/lens-proxy.ts
  packages/core/src/main/start-main-application/runnables/setup-lens-proxy.injectable.ts
  packages/core/src/renderer/components/delete-cluster-dialog/view.tsx
  packages/core/src/renderer/themes/default-theme.injectable.ts
  troubleshooting/custom-prometheus.md
Labels: rebranding
