Repository freelensapp/freelens, pull requests merged in 2025-01, with the labels that each got.

#61 The DEB package for arm64 misses binaries for kubectl, helm and k8s-proxy
  .github/workflows/integration-tests.yml
  .github/workflows/release.yml
  freelens/build/gui/electron-launch
  freelens/build/snapcraft.yaml
Labels: bug, distribution

#67 Bump year
  LICENSE
  README.md
  freelens/package.json
  packages/extension-api/package.json
Labels: chore

#69 Sync release pipeline with the latest nightly
  .github/workflows/npm-version.yaml
  .github/workflows/release.yaml
Labels: ci

#79 Use the current environment in forked process
  packages/core/src/extensions/install-extension/install-extension.injectable.ts
Labels: bug

#81 Add libasound2 and libgbm1 to Debian package
  freelens/package.json
Labels: bug, distribution

#83 Monkey patch FPM arguments to fix bug for RPM aarch64
  .github/workflows/release.yaml
Labels: bug

#85 Separate license file for binaries
  LICENSE-binaries
  freelens/package.json
Labels: chore

#87 More dependencies for RPM
  freelens/package.json
Labels: bug, distribution

#90 APT repository added to the DEB package
  freelens/package.json
Labels: distribution

#95 Include AppData metainfo in the binary packages
  .github/workflows/npm-version.yaml
  freelens/build/app.freelens.Freelens.metainfo.xml
  freelens/package.json
Labels: enhancement, distribution

#97 Use rfc822 format for APT source and xz for Packages compression
  .github/workflows/release.yaml
  README.md
  apt/freelens.sources
  freelens/build/apt/freelens.asc
  freelens/build/apt/freelens.list
  freelens/build/apt/freelens.sources
  freelens/package.json
Labels: distribution

#101 Tweak postinstall and postrm scripts
  .github/workflows/integration-tests.yaml
  .github/workflows/npm-version.yaml
  README.md
  freelens/build/after-install-deb.sh
  freelens/build/after-remove-deb.sh
  freelens/build/app.freelens.Freelens.metainfo.xml
  freelens/build/apparmor-profile.aa
  freelens/build/metainfo.xml
  freelens/package.json
Labels: distribution

#105 docs: fix link for freelens-node-pod-menu in README
  README.md
Labels: bug, documentation

#103 Fixes for apparmor profile
  freelens/build/apparmor-profile.aa
Labels: distribution

#104 Added advertisement of @freelensapp/freelens-node-pod-menu
  packages/core/src/features/extensions/__snapshots__/navigation-using-application-menu.test.ts.snap
  packages/core/src/renderer/components/extensions/extensions.tsx
Labels: ux

#109 Fix for incorrect launchable tag in metainfo file
  README.md
  freelens/build/metainfo.xml
Labels: bug, distribution

#110 More tweaks for metainfo
  freelens/build/icon.png
  freelens/build/metainfo.xml
Labels: distribution
