Repository freelensapp/freelens, pull requests merged in 2025-07, with the labels that each got.

#950 API tweaks
  .renovaterc.json5
  freelens/package.json
  knip.jsonc
  package.json
  packages/core/package.json
  packages/core/src/extensions/base-extension-store.ts
  packages/core/src/extensions/common-api/utils.ts
  packages/core/src/extensions/renderer-api/components.ts
  packages/core/src/extensions/renderer-api/k8s-api.ts
  packages/core/src/renderer/components/custom-resources/__tests__/__snapshots__/custom-resource-details.test.tsx.snap
  packages/core/src/renderer/components/custom-resources/__tests__/custom-resource-details.test.tsx
  packages/core/src/renderer/components/custom-resources/details.tsx
  packages/ensure-binaries/package.json
  packages/extensions/package.json
  packages/generate-tray-icons/package.json
  packages/kube-object/package.json
  packages/kube-object/src/kube-object.ts
  packages/kube-object/src/types/index.ts
  packages/semver/package.json
  packages/utility-features/json-api/package.json
  packages/utility-features/test-utils/package.json
  pnpm-lock.yaml
Labels: extensions, refactoring

#884 Update dependency tailwindcss to v4
  knip.jsonc
  packages/core/package.json
  packages/core/src/renderer/components/app.scss
  packages/core/src/renderer/components/catalog/catalog.module.scss
  packages/core/src/renderer/components/chart/chart.tsx
  packages/core/src/renderer/components/entity-settings/entity-settings.module.scss
  packages/core/src/renderer/components/extensions/installed-extensions.module.scss
  packages/core/src/renderer/components/layout/sidebar.module.scss
  packages/core/src/renderer/components/layout/top-bar/top-bar.module.scss
  packages/core/src/renderer/components/list/list.module.scss
  packages/core/src/renderer/components/table/react-table.scss
  packages/core/webpack/renderer.ts
  packages/infrastructure/webpack/package.json
  packages/infrastructure/webpack/src/__snapshots__/get-multi-export-config.test.ts.snap
  packages/infrastructure/webpack/src/get-react-config-for.ts
  packages/ui-components/animate/tailwind.config.js
  packages/ui-components/button/tailwind.config.js
  packages/ui-components/error-boundary/tailwind.config.js
  packages/ui-components/icon/tailwind.config.js
  packages/ui-components/notifications/tailwind.config.js
  packages/ui-components/resizing-anchor/tailwind.config.js
  packages/ui-components/spinner/tailwind.config.js
  packages/ui-components/tooltip/tailwind.config.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: updates

#947 Detect RKE2 cluster with distribution detector
  packages/core/src/main/cluster-detectors/cluster-distribution-detector.injectable.ts
Labels: enhancement

#937 Prometheus graphs ignores metrics with empty container label
  packages/technical-features/prometheus/src/operator-provider.injectable.ts.ts
Labels: bug

#966 Ephemeral containers have blue status brick
  packages/core/src/features/cluster/workloads/__snapshots__/pods.test.tsx.snap
  packages/core/src/renderer/components/node-pod-menu/__tests__/pod-menu-item.test.tsx
  packages/core/src/renderer/components/node-pod-menu/pod-attach-menu.tsx
  packages/core/src/renderer/components/node-pod-menu/pod-logs-menu.tsx
  packages/core/src/renderer/components/node-pod-menu/pod-menu-item.tsx
  packages/core/src/renderer/components/node-pod-menu/pod-shell-menu.tsx
  packages/core/src/renderer/components/status-brick/status-brick.scss
  packages/core/src/renderer/components/workloads-pods/columns/pods-containers-column.injectable.tsx
  packages/core/src/renderer/components/workloads-pods/container-status-class-name.tsx
  packages/core/src/renderer/components/workloads-pods/details/containers/pod-details-containers.tsx
  packages/core/src/renderer/components/workloads-pods/details/containers/pod-details-ephemeral-containers.tsx
  packages/core/src/renderer/components/workloads-pods/details/containers/pod-details-init-containers.tsx
  packages/core/src/renderer/components/workloads-pods/pod-details-container.scss
  packages/core/src/renderer/components/workloads-pods/pod-details-container.tsx
  packages/core/src/renderer/components/workloads/workloads-mixins.scss
  packages/kube-object/src/specifics/pod.ts
  packages/kube-object/src/types/container.ts
  packages/kube-object/src/types/ephemeral-container.ts
Labels: enhancement, ux, api

#972 API batch/v1beta1 is not supported anymore
  packages/core/src/renderer/components/kube-object-menu/kube-object-menu-items/cron-job-menu.injectable.ts
  packages/core/src/renderer/components/kube-object-menu/kube-object-menu-items/job-menu-copy.injectable.ts
Labels: breaking changes update, api

#980 Removed unused dependency @types/glob
  packages/core/package.json
  pnpm-lock.yaml
Labels: updates

#983 Complete details of Service
  .trunk/trunk.yaml
  biome.jsonc
  packages/core/src/extensions/renderer-api/components.ts
  packages/core/src/renderer/components/maybe-link/index.ts
  packages/core/src/renderer/components/maybe-link/maybe-link.tsx
  packages/core/src/renderer/components/network-services/service-details.tsx
  packages/core/src/renderer/components/network-services/service-port-component.tsx
  packages/core/src/renderer/components/workloads-pods/pod-container-port.tsx
  packages/core/src/renderer/components/workloads-pods/pod-details.tsx
  packages/core/src/renderer/template.html
  svgo.config.js
Labels: enhancement, ux, api

#985 Fix CronJobs list for sorting
  packages/core/src/renderer/components/workloads-cronjobs/cronjobs.tsx
Labels: bug

#987 Build MSI for user installation
  freelens/electron-builder.yml
Labels: distribution

#989 Additional details of the Service status
  packages/core/src/renderer/components/network-services/service-details.scss
  packages/core/src/renderer/components/network-services/service-details.tsx
  packages/kube-object/src/specifics/service.ts
Labels: ux, api

#990 Regression: patch 3rd argument has to be optional
  packages/core/src/common/k8s-api/kube-object.store.ts
Labels: extensions, regression, api

#991 API exports new LensExtensionKubeObject class
  packages/core/src/common/k8s-api/kube-object.store.ts
  packages/core/src/extensions/common-api/k8s-api.ts
Labels: enhancement, extensions, api

#1004 Show restarted containers as green and with yellow border
  packages/core/src/renderer/components/status-brick/status-brick.scss
  packages/core/src/renderer/components/workloads-pods/columns/pods-containers-column.injectable.tsx
  packages/core/src/renderer/components/workloads-pods/container-status-class-name.tsx
Labels: bug, ux, regression

#1020 Added script to migrate Biome configuration
  biome.jsonc
  package.json
Labels: ci

#1018 Fix for containers presentation in Pods list
  packages/core/src/renderer/components/workloads-pods/columns/pods-containers-column.injectable.tsx
  packages/core/src/renderer/components/workloads-pods/pod-details-container.tsx
Labels: bug, ux

#1023 Override dependency compression to ^v1.8.1
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: security, updates
