Repository freelensapp/freelens, pull requests merged in 2025-02, with the labels that each got.

#122 Change protocol name for deep links
  .github/workflows/kubectl-versions.yaml
  .renovaterc.json5
  freelens/package.json
  packages/business-features/keyboard-shortcuts/package.json
  packages/core/src/common/protocol-handler/registration.ts
  packages/core/src/common/protocol-handler/router.ts
  packages/core/src/main/catalog-sources/sync-general-catalog-entities.injectable.ts
  packages/core/src/main/electron-app/runnables/setup-deep-linking.injectable.ts
  packages/core/src/main/protocol-handler/__test__/router.test.ts
  packages/core/src/main/protocol-handler/lens-protocol-router-main/lens-protocol-router-main.ts
  packages/core/src/main/start-main-application/runnables/show-initial-window.injectable.ts
  packages/core/src/renderer/protocol-handler/bind-protocol-add-route-handlers/bind-protocol-add-route-handlers.tsx
  packages/extension-api/package.json
  packages/infrastructure/eslint-config/package.json
  packages/infrastructure/jest/package.json
  packages/infrastructure/typescript/package.json
  packages/legacy-extension-example/package.json
  packages/legacy-global-di/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/node-fetch/package.json
  packages/random-id/package.json
  packages/routing/package.json
  packages/technical-features/application/agnostic/package.json
  packages/technical-features/application/electron-main/package.json
  packages/technical-features/prometheus/package.json
  packages/ui-components/animate/package.json
  packages/ui-components/button/package.json
  packages/ui-components/error-boundary/package.json
  packages/ui-components/icon/package.json
  packages/ui-components/notifications/package.json
  packages/ui-components/resizing-anchor/package.json
  packages/ui-components/spinner/package.json
  packages/ui-components/tooltip/package.json
Labels: rebranding

#128 Regenerated icons for all OSes
  freelens/build/icon.ico
  freelens/build/icon.png
  freelens/build/icon.sh
  freelens/build/icon.svg
  freelens/build/icons/128x128.png
  freelens/build/icons/16x16.png
  freelens/build/icons/192x192.png
  freelens/build/icons/22x22.png
  freelens/build/icons/24x24.png
  freelens/build/icons/256x256.png
  freelens/build/icons/32x32.png
  freelens/build/icons/36x36.png
  freelens/build/icons/48x48.png
  freelens/build/icons/512x512.png
  freelens/build/icons/64x64.png
  freelens/build/icons/72x72.png
  freelens/build/icons/96x96.png
  freelens/build/metainfo.xml
  freelens/package.json
Labels: distribution, rebranding

#134 node-pod-menu extension is a part of the main application
  packages/core/src/renderer/components/node-pod-menu/__tests__/node-menu.test.tsx
  packages/core/src/renderer/components/node-pod-menu/__tests__/pod-attach-menu.test.tsx
  packages/core/src/renderer/components/node-pod-menu/__tests__/pod-logs-menu.test.tsx
  packages/core/src/renderer/components/node-pod-menu/__tests__/pod-menu-item.test.tsx
  packages/core/src/renderer/components/node-pod-menu/__tests__/pod-shell-menu.test.tsx
  packages/core/src/renderer/components/node-pod-menu/node-menu.tsx
  packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/node-menu.injectable.ts
  packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/pod-attach-menu.injectable.ts
  packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/pod-logs-menu.injectable.ts
  packages/core/src/renderer/components/node-pod-menu/node-pod-menu-items/pod-shell-menu.injectable.ts
  packages/core/src/renderer/components/node-pod-menu/pod-attach-menu.tsx
  packages/core/src/renderer/components/node-pod-menu/pod-logs-menu.tsx
  packages/core/src/renderer/components/node-pod-menu/pod-menu-item.tsx
  packages/core/src/renderer/components/node-pod-menu/pod-shell-menu.tsx
  packages/core/src/renderer/components/status-brick/status-brick.scss
  packages/core/src/renderer/components/workloads-pods/pods.scss
Labels: extensions

#136 Provide native icon.icns for macOS
  .gitignore
  freelens/build/icon.icns
  freelens/build/icon.ico
  freelens/build/icon.png
  freelens/build/icon.sh
  freelens/build/icons/128x128.png
  freelens/build/icons/16x16.png
  freelens/build/icons/192x192.png
  freelens/build/icons/22x22.png
  freelens/build/icons/24x24.png
  freelens/build/icons/256x256.png
  freelens/build/icons/32x32.png
  freelens/build/icons/36x36.png
  freelens/build/icons/48x48.png
  freelens/build/icons/512x512.png
  freelens/build/icons/64x64.png
  freelens/build/icons/72x72.png
  freelens/build/icons/96x96.png
Labels: distribution, rebranding

#137 Sign Windows MSI and EXE
  .github/workflows/release.yaml
Labels: distribution

#142 Use annotation rather than label for marking manual edits
  packages/core/src/features/cluster/namespaces/__snapshots__/edit-namespace-from-new-tab.test.tsx.snap
  packages/core/src/features/cluster/namespaces/edit-namespace-from-new-tab.test.tsx
  packages/core/src/renderer/components/dock/edit-resource/edit-resource-model/edit-resource-model.injectable.tsx
Labels: enhancement, rebranding

#146 Defining the mountpoints per cluster for the filesystem metrics
  packages/core/src/common/cluster-types.ts
  packages/core/src/main/routes/metrics/add-metrics-route.injectable.ts
  packages/core/src/renderer/components/cluster-settings/prometheus-setting.tsx
  packages/technical-features/prometheus/src/helm-provider.injectable.ts
  packages/technical-features/prometheus/src/lens-provider.injectable.ts
  packages/technical-features/prometheus/src/operator-provider.injectable.ts.ts
  packages/technical-features/prometheus/src/stacklight-provider.injectable.ts
Labels: bug

#147 Allows to run node shell on Bootlerocket and Windows nodes
  packages/core/src/common/cluster-types.ts
  packages/core/src/main/shell-session/node-shell-session/node-shell-session.ts
  packages/core/src/renderer/components/cluster-settings/node-shell-setting.tsx
  packages/kube-object/src/specifics/node.ts
Labels: enhancement

#153 Updated apiVersion for CronJobs from batch/v1beta1 to batch/v1
  packages/core/src/renderer/components/__tests__/cronjob.store.test.ts
  packages/core/src/renderer/components/kube-object-details/kube-object-detail-items/implementations/cron-job-detail-item.injectable.ts
  packages/resource-templates/templates/create-resource/CronJob.yaml
Labels: chore

#164 More fixes after upgrading Node and Chrome
  freelens/package.json
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/common/utils/reactive-now/reactive-now.ts
  packages/core/src/common/vars/process-arch.injectable.ts
  packages/core/src/features/application-update/child-features/periodical-checking-of-updates/main/periodical-check-for-updates.injectable.ts
  packages/core/src/features/shell-sync/main/compute-unix-shell-environment.test.ts
  packages/core/src/features/shell-sync/main/setup-shell.injectable.ts
  packages/core/src/main/shell-session/shell-session.ts
  packages/core/src/renderer/components/countdown/countdown-state.injectable.ts
  packages/core/src/renderer/hooks/useInterval.ts
  packages/core/src/renderer/kube-watch-api/kube-watch-api.ts
  packages/core/webpack/get-typescript-loader.ts
  packages/ensure-binaries/package.json
  packages/extension-api/package.json
  packages/generate-tray-icons/package.json
  packages/infrastructure/typescript/config/base.json
  packages/infrastructure/typescript/package.json
  packages/legacy-extension-example/package.json
  packages/semver/package.json
  packages/ui-components/animate/src/animate.tsx
  packages/utility-features/json-api/package.json
  packages/utility-features/utilities/src/type-narrowing.ts
  tsconfig.json
Labels: chore

#170 Removed adr package
  .gitignore
  package-lock.json
  package.json
Labels: chore

#188 Set the default shell if unset
  packages/core/src/common/vars/default-shell.global-override-for-injectable.ts
  packages/core/src/common/vars/default-shell.injectable.ts
  packages/core/src/common/vars/is-flatpak-package.injectable.ts
  packages/core/src/extensions/common-api/app.ts
  packages/core/src/features/preferences/renderer/preference-items/terminal/terminal-shell-path/default-shell/default-shell.injectable.ts
  packages/core/src/features/preferences/renderer/preference-items/terminal/terminal-shell-path/terminal-shell-path.tsx
  packages/core/src/features/shell-sync/main/compute-shell-environment.injectable.ts
  packages/core/src/features/shell-sync/main/setup-shell.injectable.ts
  packages/core/src/main/shell-session/local-shell-session/open.injectable.ts
  packages/core/src/main/shell-session/node-shell-session/open.injectable.ts
  packages/core/src/main/shell-session/shell-session.ts
Labels: bug, regression, future

#196 Removed dependency express
  package-lock.json
Labels: chore
